import React from "react";

export default function Terms() {
  return (
    <div className="pt-28 pb-24 mx-auto max-w-3xl px-6 relative z-10" data-testid="page-terms">
      <h1 className="font-heading text-4xl font-extralight tracking-tighter">Terms of Service</h1>
      <div className="glass p-6 mt-6 space-y-4 text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
        <p>EchoSplit is provided as a research project. Do not upload content you do not have the right to process.</p>
        <p>The service is provided "as is". Outputs are generated by machine learning models and may contain inaccuracies. You are responsible for validating any use of transcripts, summaries or translations.</p>
        <p>Abuse of the platform (illegal content, harassment material, PII harvesting) is prohibited and may result in account termination.</p>
      </div>
    </div>
  );
}
